spin
spin version
clear
spin
cd /home/Aldhair
cd /home
cd /Aldair
ls
cd Aldhair
cd Aldair
ls
spin hello.pml
spin hello.pml
spin hello.pml
spin Other.pml
spin Other.pml
spin Other.pml
spin Other.pml
spin Other.pml
spin Other.pml
spin Other.pml
spin Other.pml
spin Other.pml
spin Other.pml
spin Other.pml
spin Other.pml
spin Other.pml
spin Other.pml
spin Other.pml
spin Other.pml
spin Other.pml
spin Other.pml
spin Other.pml
spin Other.pml
spin Other.pml
spin Other.pml
spin Other.pml
spin Other.pml
spin Other.pml
spin Other.pml
spin Other.pml
spin Other.pml
spin Other.pml
spin Other.pml
spin Other.pml
spin Other.pml
spin Other.pml
spin Other.pml
spin Other.pml
spin Other.pml
spin Other.pml
spin Other.pml
spin Other.pml
spin Other.pml
spin Other.pml
spin Other.pml
spin Other.pml
spin Other.pml
spin Other.pml
spin Other.pml
spin Other.pml
spin Other.pml
spin Other.pml
spin Other.pml
spin Other.pml
spin Other.pml
spin Other.pml
spin Other.pml
spin Other.pml
spin Other.pml
spin Other.pml
spin Other.pml
spin Other.pml
spin Other.pml
spin Other.pml
spin Other.pml
spin Other.pml
spin Other.pml
spin Other.pml
spin Other.pml
spin Other.pml
spin Other.pml
spin Other.pml
spin Other.pml
spin Other.pml
spin Other.pml
spin Other.pml
spin Other.pml
spin Other.pml
spin Other.pml
spin Other.pml
spin Other.pml
spin Other.pml
spin Other.pml
spin Other.pml
spin Other.pml
spin Other.pml
spin Other.pml
spin Other.pml
spin Other.pml
spin Other.pml
spin Other.pml
spin Other.pml
spin Other.pml
spin Other.pml
spin Other.pml
spin Other.pml
spin Other.pml
pwd
spin Other.pml
spin Other.pml
spin Other.pml
spin Other.pml
spin Other2.pml
spin Other2.pml
spin Other2.pml
spin Other2.pml
ls
spin Signal.pml
cp Signal.pml Signal2.pml
spin Signal2.pml
spin -a Signal2.pml
gcc pan.c
